# Generated by Django 5.1.11 on 2025-07-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='domain',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
