# Generated by Django 5.1.11 on 2025-07-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_domain_resource_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_started',
        ),
        migrations.AddField(
            model_name='userproject',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='core.step'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
