# Generated by Django 5.1.11 on 2025-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
