# Generated by Django 5.1.11 on 2025-07-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userproject_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='is_completed',
        ),
    ]
