# Generated by Django 5.1.11 on 2025-07-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(default=list),
        ),
    ]
